// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apiOperadores.Models
{
    public partial class Bitacora
    {
        public int Id { get; set; }
        public int? FkUsuarioId { get; set; }
        public string TablaAfectada { get; set; }
        public string TipoMovimiento { get; set; }
        public string CamposAfectados { get; set; }
        public DateTime? FechaMovimiento { get; set; }
    }
}