// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apiOperadores.Models
{
    public partial class Operadore
    {
        public int? Id { get; set; }
        public int? FkSucursalId { get; set; }
        public string Sucursal { get; set; }
        public int? FkPuestoId { get; set; }
        public string Puesto { get; set; }
        public int? FkPerfilId { get; set; }
        public string Perfil { get; set; }
        public int? FkTipoId { get; set; }
        public string TipoEmpleado { get; set; }
        public int? NumeroEmpleado { get; set; }
        public string Contrasena { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string FotoPerfil { get; set; }
        public string TelefonoCelular { get; set; }
        public string CorreoElectronico { get; set; }
        public string Rfc { get; set; }
        public string Curp { get; set; }
        public int? Nss { get; set; }
        public string Direccion { get; set; }
        public int? FkTipoContratoId { get; set; }
        public string TipoContrato { get; set; }
        public string Genero { get; set; }
        public string Afore { get; set; }
        public int? FkEstadoCivilId { get; set; }
        public string EstadoCivil { get; set; }
        public int? KmsAcumulados { get; set; }
        public int? FkExperienciaId { get; set; }
        public string ExperienciaLaboral { get; set; }
        public int? FkNivelEcolaridadId { get; set; }
        public string NivelEstudio { get; set; }
        public string NombreConyuge { get; set; }
        public int? TotalHijos { get; set; }
        public string TelefonoEmergencias { get; set; }
        public DateTime? FechaBaja { get; set; }
        public int? FkCausaBajaId { get; set; }
        public string CausaBaja { get; set; }
        public bool? StatusSesion { get; set; }
        public DateTime? FechaInicioSesion { get; set; }
        public string DispositivoInicioSesion { get; set; }
        public string DispositivoNotificaciones { get; set; }
        public int? FkEstadoOperadorId { get; set; }
        public string? EstadoEmpleado { get; set; }
        public int? FkUsuarioRegistro { get; set; }
        public DateTime FechaRegistro { get; set; }
        public bool? SisStatus { get; set; }

        public string? UsuarioRegistroNombre { get; set; }
        public string? UsuarioRegistroApellidoPaterno { get; set; }
        public string? UsuarioRegistroApellidoMaterno { get; set; }
        public string? UsuarioRegistroPerfilAlias { get; set; }
        public string? UsuarioRegistroDepartamentoColor { get; set; }
    }
}