// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apiOperadores.Models
{
    public partial class OperadoresStatus
    {
        public int? Id { get; set; }
        public string? Tipo { get; set; }
        public string? Nombre { get; set; }
        public string Descripcio { get; set; }
        public string ValorExtra { get; set; }
        public DateTime FechaRegistro { get; set; }
        public int? FkUsuarioRegistro { get; set; }
        public bool? SisStatus { get; set; }
        public string ValorExtra2 { get; set; }
        
        public string? UsuarioRegistroNombre { get; set; }
        public string? UsuarioRegistroApellidoPaterno { get; set; }
        public string? UsuarioRegistroApellidoMaterno { get; set; }
        public string? UsuarioRegistroPerfilAlias { get; set; }
        public string? UsuarioRegistroDepartamentoColor { get; set; }

    }
}