// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace apiOperadores.Models
{
    public partial class Usuario
    {
        public int Id { get; set; }
        public bool PerfilStatus { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public bool tipoUsuario { get; set; }
        public string CorreoElectronico { get; set; }
        public string PerfilAlias { get; set; }
        public string PuestoNombre { get; set; }
        public string DepartamentoNombre { get; set; }
        public string DepartamentoColor { get; set; }
        public bool? StatusSesion { get; set; }
        public bool? SisStatus { get; set; }
        public bool? tipoPermiso { get; set; }
    }
}